"""add roles to users

Revision ID: 0a620eb16c90
Revises: 814cc2e71aa5
Create Date: 2026-05-18 11:26:12.914617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0a620eb16c90'
down_revision: Union[str, Sequence[str], None] = '814cc2e71aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rol',
    sa.Column('idRol', sa.Integer(), nullable=False),
    sa.Column('rolNombre', sa.String(length=30), nullable=False),
    sa.Column('rolDescripcion', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('rolEstado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('idRol'),
    sa.UniqueConstraint('rolNombre')
    )
    rol_table = sa.table(
        'rol',
        sa.column('rolNombre', sa.String),
        sa.column('rolDescripcion', sa.String),
        sa.column('rolEstado', sa.Boolean),
    )
    op.bulk_insert(
        rol_table,
        [
            {
                'rolNombre': 'admin',
                'rolDescripcion': 'Administrador del sistema',
                'rolEstado': True,
            },
            {
                'rolNombre': 'cajero',
                'rolDescripcion': 'Gestiona caja y pagos',
                'rolEstado': True,
            },
            {
                'rolNombre': 'vendedor',
                'rolDescripcion': 'Gestiona ventas y clientes',
                'rolEstado': True,
            },
            {
                'rolNombre': 'contador',
                'rolDescripcion': 'Gestiona contabilidad y reportes',
                'rolEstado': True,
            },
        ],
    )
    op.add_column('usuario', sa.Column('idRol', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_usuario_idRol_rol', 'usuario', 'rol', ['idRol'], ['idRol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_usuario_idRol_rol', 'usuario', type_='foreignkey')
    op.drop_column('usuario', 'idRol')
    op.drop_table('rol')
    # ### end Alembic commands ###
