"""initial schema

Revision ID: 814cc2e71aa5
Revises: 
Create Date: 2026-05-18 10:50:38.757337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '814cc2e71aa5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('almacen',
    sa.Column('idAlmacen', sa.Integer(), nullable=False),
    sa.Column('almNombre', sqlmodel.sql.sqltypes.AutoString(length=35), nullable=False),
    sa.Column('almPercha', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
    sa.Column('almEstante', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
    sa.PrimaryKeyConstraint('idAlmacen')
    )
    op.create_table('categoria',
    sa.Column('idCategoria', sa.Integer(), nullable=False),
    sa.Column('catNombre', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idCategoria')
    )
    op.create_table('cliente',
    sa.Column('idCliente', sa.Integer(), nullable=False),
    sa.Column('cedula', sqlmodel.sql.sqltypes.AutoString(length=13), nullable=False),
    sa.Column('cli_nombre', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('fono', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(length=55), nullable=False),
    sa.Column('c_descripcion', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column('cli_mail', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idCliente')
    )
    op.create_table('configcorreo',
    sa.Column('idConfigCorreo', sa.Integer(), nullable=False),
    sa.Column('correoEnviador', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('claveAplicacion', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
    sa.Column('correoReceptor1', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('correoReceptor2', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('respaldo', sa.Integer(), nullable=False),
    sa.Column('correo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idConfigCorreo')
    )
    op.create_table('impuesto',
    sa.Column('idImpuesto', sa.Integer(), nullable=False),
    sa.Column('impNombre', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('impValor', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idImpuesto')
    )
    op.create_table('kardex',
    sa.Column('idKardex', sa.Integer(), nullable=False),
    sa.Column('kar_tipo', sa.Integer(), nullable=False),
    sa.Column('kar_fecha', sa.Date(), nullable=False),
    sa.Column('kar_hora', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('kar_motivo', sqlmodel.sql.sqltypes.AutoString(length=90), nullable=False),
    sa.Column('kar_cant_ingreso', sa.Float(), nullable=False),
    sa.Column('kar_cant_egreso', sa.Float(), nullable=False),
    sa.Column('kar_saldo_anterior', sa.Float(), nullable=False),
    sa.Column('kar_saldo_actual', sa.Float(), nullable=False),
    sa.Column('kar_observacion', sqlmodel.sql.sqltypes.AutoString(length=90), nullable=False),
    sa.Column('idInvOrigen', sa.Integer(), nullable=False),
    sa.Column('kar_almacen_origen', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('ker_almacen_destino', sqlmodel.sql.sqltypes.AutoString(length=35), nullable=False),
    sa.Column('idArticulo', sa.Integer(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idKardex')
    )
    op.create_table('marca',
    sa.Column('idMarca', sa.Integer(), nullable=False),
    sa.Column('marNombre', sqlmodel.sql.sqltypes.AutoString(length=35), nullable=False),
    sa.PrimaryKeyConstraint('idMarca')
    )
    op.create_table('nota',
    sa.Column('idNota', sa.Integer(), nullable=False),
    sa.Column('not_fecha', sa.Date(), nullable=False),
    sa.Column('not_cliente', sqlmodel.sql.sqltypes.AutoString(length=55), nullable=False),
    sa.Column('not_descripcion', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('cliente_idCliente', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idNota')
    )
    op.create_table('proveedor',
    sa.Column('idProveedor', sa.Integer(), nullable=False),
    sa.Column('proRuc', sqlmodel.sql.sqltypes.AutoString(length=13), nullable=False),
    sa.Column('proNombre', sqlmodel.sql.sqltypes.AutoString(length=55), nullable=False),
    sa.Column('proCiudad', sqlmodel.sql.sqltypes.AutoString(length=35), nullable=False),
    sa.Column('proDireccion', sqlmodel.sql.sqltypes.AutoString(length=85), nullable=False),
    sa.Column('proTelefono', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('proCelular', sqlmodel.sql.sqltypes.AutoString(length=21), nullable=False),
    sa.Column('proMail', sqlmodel.sql.sqltypes.AutoString(length=35), nullable=False),
    sa.Column('proBanco1', sqlmodel.sql.sqltypes.AutoString(length=35), nullable=False),
    sa.Column('proBanco2', sqlmodel.sql.sqltypes.AutoString(length=35), nullable=False),
    sa.Column('proCuenta1', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.Column('proCuenta2', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.Column('proTipoCuenta1', sa.Integer(), nullable=False),
    sa.Column('proTipoCuenta2', sa.Integer(), nullable=False),
    sa.Column('proProducto', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('proEstado', sa.Boolean(), nullable=False),
    sa.Column('proColor', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
    sa.PrimaryKeyConstraint('idProveedor')
    )
    op.create_table('usuario',
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('userCedula', sqlmodel.sql.sqltypes.AutoString(length=13), nullable=False),
    sa.Column('userNombre', sqlmodel.sql.sqltypes.AutoString(length=35), nullable=False),
    sa.Column('userApellido', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('userFono', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('userDireccion', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column('userFecha', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('userMail', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column('userUsuario', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('userClave', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('userEstado', sa.Boolean(), nullable=True),
    sa.Column('userPrincipal', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('idUsuario')
    )
    op.create_table('articulo',
    sa.Column('idArticulo', sa.Integer(), nullable=False),
    sa.Column('artCodigo', sqlmodel.sql.sqltypes.AutoString(length=35), nullable=False),
    sa.Column('artDescripcion', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('artCosto', sa.Float(), nullable=False),
    sa.Column('artPVP', sa.Float(), nullable=False),
    sa.Column('artPVMayorista', sa.Float(), nullable=False),
    sa.Column('artPVMinimo', sa.Float(), nullable=False),
    sa.Column('artSerie', sa.Integer(), nullable=False),
    sa.Column('artStockMin', sa.Integer(), nullable=False),
    sa.Column('artEstado', sa.Integer(), nullable=False),
    sa.Column('categoria_idCategoria', sa.Integer(), nullable=False),
    sa.Column('marca_idMarca', sa.Integer(), nullable=False),
    sa.Column('impuesto_idImpuesto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_idCategoria'], ['categoria.idCategoria'], ),
    sa.ForeignKeyConstraint(['impuesto_idImpuesto'], ['impuesto.idImpuesto'], ),
    sa.ForeignKeyConstraint(['marca_idMarca'], ['marca.idMarca'], ),
    sa.PrimaryKeyConstraint('idArticulo')
    )
    op.create_table('credito',
    sa.Column('idCreditoCliente', sa.Integer(), nullable=False),
    sa.Column('creditoFecha', sa.Date(), nullable=False),
    sa.Column('creditoEntrada', sa.Float(), nullable=False),
    sa.Column('creditoSaldo', sa.Float(), nullable=False),
    sa.Column('creditoTotal', sa.Float(), nullable=False),
    sa.Column('Cliente_idCliente', sa.Integer(), nullable=False),
    sa.Column('Usuario_idUsuario', sa.Integer(), nullable=False),
    sa.Column('creditoEstado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Cliente_idCliente'], ['cliente.idCliente'], ),
    sa.ForeignKeyConstraint(['Usuario_idUsuario'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idCreditoCliente')
    )
    op.create_table('descuentocliente',
    sa.Column('idDescuento', sa.Integer(), nullable=False),
    sa.Column('des_tipo', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
    sa.Column('des_porcentaje', sa.Float(), nullable=False),
    sa.Column('des_condicion', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('categoria_idCategoria', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_idCategoria'], ['categoria.idCategoria'], ),
    sa.PrimaryKeyConstraint('idDescuento')
    )
    op.create_table('facturasproveedor',
    sa.Column('idFacturaProveedor', sa.Integer(), nullable=False),
    sa.Column('fpFactura', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
    sa.Column('fpSubtotal', sa.Float(), nullable=False),
    sa.Column('fpSubtotal0', sa.Float(), nullable=False),
    sa.Column('fpIva', sa.Float(), nullable=False),
    sa.Column('fpTotal', sa.Float(), nullable=False),
    sa.Column('fpCredito', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.Column('fpFecha', sa.Date(), nullable=False),
    sa.Column('fpPlazo', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('Usuario_idUsuario', sa.Integer(), nullable=False),
    sa.Column('proveedor_idProveedor', sa.Integer(), nullable=False),
    sa.Column('fpSaldo', sa.Float(), nullable=False),
    sa.Column('fpAbono', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['Usuario_idUsuario'], ['usuario.idUsuario'], ),
    sa.ForeignKeyConstraint(['proveedor_idProveedor'], ['proveedor.idProveedor'], ),
    sa.PrimaryKeyConstraint('idFacturaProveedor')
    )
    op.create_table('ingresocaja',
    sa.Column('idIngreso', sa.Integer(), nullable=False),
    sa.Column('cajaIngreso', sa.Float(), nullable=False),
    sa.Column('cajaEgreso', sa.Float(), nullable=False),
    sa.Column('cajaConcepto', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('cajaFecha', sa.Date(), nullable=False),
    sa.Column('cajaHora', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('usuario_idUsuario', sa.Integer(), nullable=False),
    sa.Column('idDeposito', sa.Integer(), nullable=False),
    sa.Column('idFactura', sa.Integer(), nullable=False),
    sa.Column('idVenta', sa.Integer(), nullable=False),
    sa.Column('idOrden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_idUsuario'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idIngreso')
    )
    op.create_table('ordentrabajo',
    sa.Column('idOrden', sa.Integer(), nullable=False),
    sa.Column('doNumero', sa.Integer(), nullable=False),
    sa.Column('doFechaIngreso', sa.Date(), nullable=False),
    sa.Column('doFechaSalida', sa.Date(), nullable=False),
    sa.Column('doTotal', sa.Float(), nullable=False),
    sa.Column('doSaldo', sa.Float(), nullable=False),
    sa.Column('doAbono', sa.Float(), nullable=False),
    sa.Column('cliente_idCliente', sa.Integer(), nullable=False),
    sa.Column('usuario_idUsuario', sa.Integer(), nullable=False),
    sa.Column('doEstado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_idCliente'], ['cliente.idCliente'], ),
    sa.ForeignKeyConstraint(['usuario_idUsuario'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idOrden')
    )
    op.create_table('pagosproveedor',
    sa.Column('idPagosproveedor', sa.Integer(), nullable=False),
    sa.Column('pp_estado', sa.Boolean(), nullable=False),
    sa.Column('pp_factura', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('pp_fechaemision', sa.Date(), nullable=False),
    sa.Column('pp_Numerorecibo', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('pp_formapago', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('pp_cheque', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('pp_valorcheque', sa.Float(), nullable=False),
    sa.Column('pp_banco', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('pp_destino', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('pp_fechapago', sa.Date(), nullable=False),
    sa.Column('pp_valor', sa.Float(), nullable=False),
    sa.Column('pp_saldo', sa.Float(), nullable=False),
    sa.Column('pp_fechaqpago', sa.Date(), nullable=False),
    sa.Column('pp_observacion', sqlmodel.sql.sqltypes.AutoString(length=75), nullable=False),
    sa.Column('usuario_idUsuario', sa.Integer(), nullable=False),
    sa.Column('proveedor_idFactura', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_idUsuario'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idPagosproveedor')
    )
    op.create_table('pedido',
    sa.Column('idPedido', sa.Integer(), nullable=False),
    sa.Column('pedNombre', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column('pedFecha', sa.Date(), nullable=False),
    sa.Column('pedObservacion', sqlmodel.sql.sqltypes.AutoString(length=65), nullable=False),
    sa.Column('usuario_idUsuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_idUsuario'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idPedido')
    )
    op.create_table('proforma',
    sa.Column('idProforma', sa.Integer(), nullable=False),
    sa.Column('pro_subtotal14', sa.Float(), nullable=False),
    sa.Column('pro_subtotal0', sa.Float(), nullable=False),
    sa.Column('pro_descuento', sa.Float(), nullable=False),
    sa.Column('pro_subtotalSinImp', sa.Float(), nullable=False),
    sa.Column('pro_iva0', sa.Float(), nullable=False),
    sa.Column('pro_iva', sa.Float(), nullable=False),
    sa.Column('pro_total', sa.Float(), nullable=False),
    sa.Column('pro_fecha', sa.Date(), nullable=False),
    sa.Column('pro_descripsion', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column('pro_plazo', sa.Integer(), nullable=False),
    sa.Column('cliente_idCliente', sa.Integer(), nullable=False),
    sa.Column('usuario_idUsuario', sa.Integer(), nullable=False),
    sa.Column('comprobante', sa.Integer(), nullable=False),
    sa.Column('pro_Estado', sa.Integer(), nullable=False),
    sa.Column('pro_tipoCredito', sa.Integer(), nullable=False),
    sa.Column('pro_Impuesto', sa.Integer(), nullable=False),
    sa.Column('pro_opiva', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_idCliente'], ['cliente.idCliente'], ),
    sa.ForeignKeyConstraint(['usuario_idUsuario'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idProforma')
    )
    op.create_table('asignardescuento',
    sa.Column('idAsignar', sa.Integer(), nullable=False),
    sa.Column('cliente_idCliente', sa.Integer(), nullable=False),
    sa.Column('descuento_idDescuento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_idCliente'], ['cliente.idCliente'], ),
    sa.ForeignKeyConstraint(['descuento_idDescuento'], ['descuentocliente.idDescuento'], ),
    sa.PrimaryKeyConstraint('idAsignar')
    )
    op.create_table('deposito',
    sa.Column('idDeposito', sa.Integer(), nullable=False),
    sa.Column('dFecha', sa.Date(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=False),
    sa.Column('Deposito', sa.Float(), nullable=False),
    sa.Column('concepto', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('comprobante', sa.Integer(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column('credito_idCreditoCliente', sa.Integer(), nullable=False),
    sa.Column('usuario_idUsuario', sa.Integer(), nullable=False),
    sa.Column('idFactura', sa.Integer(), nullable=False),
    sa.Column('tipoPago', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['credito_idCreditoCliente'], ['credito.idCreditoCliente'], ),
    sa.ForeignKeyConstraint(['usuario_idUsuario'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idDeposito')
    )
    op.create_table('detallecompras',
    sa.Column('idCompras', sa.Integer(), nullable=False),
    sa.Column('com_cantidad', sa.Integer(), nullable=False),
    sa.Column('com_valorunitario', sa.Float(), nullable=False),
    sa.Column('com_valortotal', sa.Float(), nullable=False),
    sa.Column('facturasProveedor_idFacturaProveedor', sa.Integer(), nullable=False),
    sa.Column('idInventario', sa.Integer(), nullable=False),
    sa.Column('Articulo_idArticulo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facturasProveedor_idFacturaProveedor'], ['facturasproveedor.idFacturaProveedor'], ),
    sa.PrimaryKeyConstraint('idCompras')
    )
    op.create_table('detalleorden',
    sa.Column('idDetalleOrden', sa.Integer(), nullable=False),
    sa.Column('otMarca', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
    sa.Column('otModelo', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
    sa.Column('otSerie', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('otDanio', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('otObservacion', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column('otEstado', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column('otEstadoReparacion', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('otTecnico', sqlmodel.sql.sqltypes.AutoString(length=35), nullable=False),
    sa.Column('otValor', sa.Float(), nullable=False),
    sa.Column('otAbono', sa.Float(), nullable=False),
    sa.Column('ordentrabajo_idOrden', sa.Integer(), nullable=False),
    sa.Column('otFacturado', sa.Integer(), nullable=False),
    sa.Column('otNunEntrega', sa.Integer(), nullable=False),
    sa.Column('impuesto_idImpuesto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ordentrabajo_idOrden'], ['ordentrabajo.idOrden'], ),
    sa.PrimaryKeyConstraint('idDetalleOrden')
    )
    op.create_table('detallepedido',
    sa.Column('idDetallePedido', sa.Integer(), nullable=False),
    sa.Column('pedCantidad', sa.Integer(), nullable=False),
    sa.Column('pedDescripcion', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('pedido_idPedido', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_idPedido'], ['pedido.idPedido'], ),
    sa.PrimaryKeyConstraint('idDetallePedido')
    )
    op.create_table('detalleproforma',
    sa.Column('idDetalleProforma', sa.Integer(), nullable=False),
    sa.Column('detpro_cantidad', sa.Integer(), nullable=False),
    sa.Column('detpro_valorUnitario', sa.Float(), nullable=False),
    sa.Column('detpro_det_descuento', sa.Float(), nullable=False),
    sa.Column('detpro_valorTotal', sa.Float(), nullable=False),
    sa.Column('proforma_idProforma', sa.Integer(), nullable=False),
    sa.Column('inventario_idInventario', sa.Integer(), nullable=False),
    sa.Column('idVenta', sa.Integer(), nullable=False),
    sa.Column('idOrdenTrabajo', sa.Integer(), nullable=False),
    sa.Column('detpro_detValorConImpuesto', sa.Float(), nullable=False),
    sa.Column('idTalla', sa.Integer(), nullable=False),
    sa.Column('idSerie', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proforma_idProforma'], ['proforma.idProforma'], ),
    sa.PrimaryKeyConstraint('idDetalleProforma')
    )
    op.create_table('factura',
    sa.Column('idFactura', sa.Integer(), nullable=False),
    sa.Column('subtotal14', sa.Float(), nullable=False),
    sa.Column('subtotal0', sa.Float(), nullable=False),
    sa.Column('descuento', sa.Float(), nullable=False),
    sa.Column('subtotalSinImp', sa.Float(), nullable=False),
    sa.Column('iva0', sa.Float(), nullable=False),
    sa.Column('iva', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripsion', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column('plazo', sa.Integer(), nullable=False),
    sa.Column('fEntrada', sa.Float(), nullable=False),
    sa.Column('fSaldo', sa.Float(), nullable=False),
    sa.Column('utilidad', sa.Float(), nullable=False),
    sa.Column('cliente_idCliente', sa.Integer(), nullable=False),
    sa.Column('credito_idCreditoCliente', sa.Integer(), nullable=False),
    sa.Column('usuario_idUsuario', sa.Integer(), nullable=False),
    sa.Column('secuencia', sa.Integer(), nullable=False),
    sa.Column('ptoEmicion', sa.Integer(), nullable=False),
    sa.Column('establecimiento', sa.Integer(), nullable=False),
    sa.Column('comprobante', sa.Integer(), nullable=False),
    sa.Column('facEstado', sa.Integer(), nullable=False),
    sa.Column('tipoCredito', sa.Integer(), nullable=False),
    sa.Column('facImpuesto', sa.Integer(), nullable=False),
    sa.Column('fac_claveacceso', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('fac_sriestado', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
    sa.Column('fac_enviocliente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_idCliente'], ['cliente.idCliente'], ),
    sa.ForeignKeyConstraint(['credito_idCreditoCliente'], ['credito.idCreditoCliente'], ),
    sa.ForeignKeyConstraint(['usuario_idUsuario'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idFactura')
    )
    op.create_table('inventario',
    sa.Column('idInventario', sa.Integer(), nullable=False),
    sa.Column('invCantidad', sa.Integer(), nullable=False),
    sa.Column('invStock', sa.Integer(), nullable=False),
    sa.Column('invEstado', sa.Integer(), nullable=False),
    sa.Column('almacen_idAlmacen', sa.Integer(), nullable=False),
    sa.Column('articulo_idArticulo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['almacen_idAlmacen'], ['almacen.idAlmacen'], ),
    sa.ForeignKeyConstraint(['articulo_idArticulo'], ['articulo.idArticulo'], ),
    sa.PrimaryKeyConstraint('idInventario')
    )
    op.create_table('detalle',
    sa.Column('idDetalle', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('codPrincipal', sqlmodel.sql.sqltypes.AutoString(length=35), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=55), nullable=False),
    sa.Column('valorUnitario', sa.Float(), nullable=False),
    sa.Column('det_descuento', sa.Float(), nullable=False),
    sa.Column('valorTotal', sa.Float(), nullable=False),
    sa.Column('factura_idFactura', sa.Integer(), nullable=False),
    sa.Column('inventario_idInventario', sa.Integer(), nullable=False),
    sa.Column('idVenta', sa.Integer(), nullable=False),
    sa.Column('idOrdenTrabajo', sa.Integer(), nullable=False),
    sa.Column('detValorConImpuesto', sa.Float(), nullable=False),
    sa.Column('idTalla', sa.Integer(), nullable=False),
    sa.Column('idSerie', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['factura_idFactura'], ['factura.idFactura'], ),
    sa.PrimaryKeyConstraint('idDetalle')
    )
    op.create_table('guardarventa',
    sa.Column('idGuardarVenta', sa.Integer(), nullable=False),
    sa.Column('factura_idFactura', sa.Integer(), nullable=False),
    sa.Column('gvFecha', sa.Date(), nullable=False),
    sa.Column('gvNombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.ForeignKeyConstraint(['factura_idFactura'], ['factura.idFactura'], ),
    sa.PrimaryKeyConstraint('idGuardarVenta')
    )
    op.create_table('serie',
    sa.Column('idSerie', sa.Integer(), nullable=False),
    sa.Column('serieNun1', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('serieNun2', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('serieStock', sa.Integer(), nullable=False),
    sa.Column('articulo_idArticulo', sa.Integer(), nullable=False),
    sa.Column('inventario_idInventario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['articulo_idArticulo'], ['articulo.idArticulo'], ),
    sa.ForeignKeyConstraint(['inventario_idInventario'], ['inventario.idInventario'], ),
    sa.PrimaryKeyConstraint('idSerie')
    )
    op.create_table('talla',
    sa.Column('idTalla', sa.Integer(), nullable=False),
    sa.Column('tallaCantidad', sa.Integer(), nullable=False),
    sa.Column('talTalla', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
    sa.Column('articulo_idArticulo', sa.Integer(), nullable=False),
    sa.Column('inventario_idInventario', sa.Integer(), nullable=False),
    sa.Column('tallaCodigo', sqlmodel.sql.sqltypes.AutoString(length=35), nullable=False),
    sa.ForeignKeyConstraint(['articulo_idArticulo'], ['articulo.idArticulo'], ),
    sa.ForeignKeyConstraint(['inventario_idInventario'], ['inventario.idInventario'], ),
    sa.PrimaryKeyConstraint('idTalla')
    )
    op.create_table('ventadeldia',
    sa.Column('idVenta', sa.Integer(), nullable=False),
    sa.Column('ven_Fecha', sa.Date(), nullable=False),
    sa.Column('ven_Hora', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('ven_Codigo', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('ven_Cantidad', sa.Integer(), nullable=False),
    sa.Column('ven_Descripcion', sqlmodel.sql.sqltypes.AutoString(length=75), nullable=False),
    sa.Column('ven_Costo', sa.Float(), nullable=False),
    sa.Column('ven_Utilidad', sa.Float(), nullable=False),
    sa.Column('ven_Estado', sa.Integer(), nullable=False),
    sa.Column('inventario_idInventario', sa.Integer(), nullable=False),
    sa.Column('usuario_idUsuario', sa.Integer(), nullable=False),
    sa.Column('idTalla', sa.Integer(), nullable=False),
    sa.Column('idSerie', sa.Integer(), nullable=False),
    sa.Column('impuesto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inventario_idInventario'], ['inventario.idInventario'], ),
    sa.ForeignKeyConstraint(['usuario_idUsuario'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idVenta')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ventadeldia')
    op.drop_table('talla')
    op.drop_table('serie')
    op.drop_table('guardarventa')
    op.drop_table('detalle')
    op.drop_table('inventario')
    op.drop_table('factura')
    op.drop_table('detalleproforma')
    op.drop_table('detallepedido')
    op.drop_table('detalleorden')
    op.drop_table('detallecompras')
    op.drop_table('deposito')
    op.drop_table('asignardescuento')
    op.drop_table('proforma')
    op.drop_table('pedido')
    op.drop_table('pagosproveedor')
    op.drop_table('ordentrabajo')
    op.drop_table('ingresocaja')
    op.drop_table('facturasproveedor')
    op.drop_table('descuentocliente')
    op.drop_table('credito')
    op.drop_table('articulo')
    op.drop_table('usuario')
    op.drop_table('proveedor')
    op.drop_table('nota')
    op.drop_table('marca')
    op.drop_table('kardex')
    op.drop_table('impuesto')
    op.drop_table('configcorreo')
    op.drop_table('cliente')
    op.drop_table('categoria')
    op.drop_table('almacen')
    # ### end Alembic commands ###
